### ISSUE TITLE
Improve serviceDescription.json format

### ISSUE THREAD

**Issue by xapasnon** [JohnDoeInvest/ms-visualization#1]
Now that we have started a) building this tool and b) using it on real services we see a need for more types/definitions. 

In essence we need to extend the current format so that:
- We can define groups/controllers as a parent level to REST api endpoints. This will allow us to do expand/collapse of long lists of methods AND to work on code that generates Express routes based on this file which would "guarantee" a match between the documentation and the code. Example: 
    - a microservice has two "main endpoints" `/sports` and `/events`. These are the groups/controllers.
    - within each of these groups the `GET/POST/PUT` endpoints are defined. Each one with a name that maps to a class/module in code.
- We want to be able to define if a REST api endpoint is "internal" or "external". The aim here is to be able to ensure security at a later stage, but also allow to draw connectors/path between two microservices that uses internal REST calls to communicate (i.e. not Kafka/event driven calls). Example:
    - each endpoint (or possibly inherited as default from the group/controller level, but should be possible to override on each entry) defines `"internal": true/false` If we don't want to lock us in, we could go for something like `"scope": ""` instead where scope could be `"internal" "external" "both" "admin"` and so on...
- Most services will need to initiate REST calls as well. So we need to be able to define both "incoming" (that we do now) and "outgoing" calls/endpoints. Example:
    - instead of the current `restAPI` we should do `restIncoming `and `restOutgoing`. Again, ideally we don't lock ourself in with REST here. Maybe we should define `incoming/exposes/...` and `outgoing/uses/...` and define REST as an entry in that array. Probably we should go down this route.

I know @Meisolsson is working on this and he will post his findings here.

**Comment by Meisolsson** [comment]
For the `restAPI` part me and Stefan have different initial thoughts. My approach, since we have decided on three main paths (admin, external, client) would be the following:
```json
{ 
  "restAPI": {
    "pathPrefix": "/authenticate/bankid",
    "admin": [],
    "external": [],
    "client": [
      {
        "uri": "/",
        "method": "POST",
        "handlingFunction": "handleAuthenticate",
        "parameters": {
          "ssid": "string with Swedish social security number"
        }
      }
    ]
  },
}
```
From my reading of Stefans inital thoguhts it would be something like:
```json
{
  "restAPI": {
    "pathPrefix": "/authenticate/bankid",
    "endpoints": {
      "/": [
        {
          "method": "POST",
          "type": "CLIENT",
          "handlingFunction": "handleAuthenticate",
          "parameters": {
            "ssid": "string with Swedish social security number"
          }
        }
      ]
    }
  },
}
```

* In both cases the `handlingFunction` would be the fuction handling the given request.
* Regarding:
    > instead of the current restAPI we should do restIncoming and restOutgoing. Again, ideally we don't lock ourself in with REST here. Maybe we should define incoming/exposes/... and outgoing/uses/... and define REST as an entry in that array. Probably we should go down this route.
    
    I think that we should keep the restAPI to REST. It's better to add other xxAPI later. If we have to group the incoming and outgoing endpoints we should do it a level above like:
    ```json
    {
        "incoming": {
            "rest": {
                ...
            }
        },

        "outgoing": {
            "rest": {
                ...
            }
        }
    }
    ```
    And even here the REST for outgoing sounds weird. Probably should be `http` or something. 
    
    Something which quickly become weird is how you define an outgoing request. For instance we have the BankID requests which it would make sense to define as just `bankId` but it makes just as much sense to file them under `rest` and then the given paths. We will probably have more things like this which we maybe just have a library for where we don't know how it does the communication.

    So the question here is how much we care about the different requests for these things. For some we might just give a description with a link to documentation or the library.



So this is my first draft, feel free to comment on it
```json
{
    "name": "authenticate-bankid",
    "description": "Accepts a Swedish social security number (SSID) and interfaces with the BankID service",
    "envVars": [],
    "incoming": {
        "restAPI": {
            "pathPrefix": "/authenticate/bankid",
            "endpoints": {
                "/": [
                    {
                        "method": "POST",
                        "type": "CLIENT",
                        "handlingFunction": "handleAuthenticate",
                        "description": "Checks the SSID and then starts an authentication",
                        "parameters": {
                            "ssid": "string with Swedish social security number"
                        }
                    }
                ]
            }
        }
    },
    "outgoing": {
        "bankid": {
            "description": "Communication is done by https://github.com/anyfin/bankid"
        }
    },
    "services": {
        "shared": {
            "redis": {},
            "kafka": {
                "consumes": [
                    "clientrequests",
                    "authenticate-bankid"
                ],
                "produces": [
                    "clientrequests",
                    "authenticate-bankid"
                ]
            }
        },
        "local": {
            "sqllite": {
                "db": {
                    "authenticate-bankid": {
                        "tables": [
                            "authenticate-bankid"
                        ]
                    }
                }
            }
        }
    }
}
```

**Comment by Meisolsson** [comment]
As an example of the gamelists for both the routing question and the function question:
```json
{
  "restAPI": {
    "pathPrefix": "/gamelists",
    "endpoints": {
      "/sports": [
        {
          "method": "GET",
          "type": "CLIENT",
          "handlingFunction": "listSports",
        }
      ],
      "/matches": [
        {
          "method": "GET",
          "type": "CLIENT",
          "handlingFunction": "listMatches",
        }
      ],
      "/competitions": [
        {
          "method": "GET",
          "type": "CLIENT",
          "handlingFunction": "listCompetitions",
        }
      ]
    }
  },
}
```

This would create the following endpoints connected to a function each:
|Method|Path|Function|
|---|---|---|
| GET | /gamelists/sports       | listSports |
| GET | /gamelists/matches      | listMatches|
| GET | /gamelists/competitions | listCompetitions |

My issue with doing a handlingClass is around how we do the function names. We could do something like { "/gamelists/sports": THE_FUNCTION } and export that in the class, but then generating the routing from the description is kind of a waste. The second option is of course to name the functions like gamelists_sports (just replacing the '/' with a '_') but that makes the code look weird, at least to me.

The second issue I have is that if we do a handlingClass we would have to dynamically load the file when we create the router. Having a handlingFunction does push the importing parts over to the coder but rather that since we then have more control over where the code lives and how it works.

For the last part I now understand it a bit better. So my suggestion is this:
```json
{
    "outgoing": {
        "bankid": {
            "description": "Communication is done by https://github.com/anyfin/bankid"
        },
        "microservices": {
            "some-microservice-name": {}
        }
    }
}
```

Not sure what we'd like to know more than that it's a microservice and it's name. So the value for `some-microservice-name` can be what ever, from what you wrote I guess you want it to be an array like `/sports` in the first example.

**Comment by xapasnon** [comment]
I think this is more than enough for taking the next step of the fileformat - nice work!

Let's keep this issue open until we have resolved the other "core ones" and then we'll change the examples and modify the parser.

**Comment by xapasnon** [comment]
Closing this as we have now adapted a new version based on the discussions above. The main document/readme will be updated with proper example.
